### PR TITLE
update package.json for publish

### PR DESCRIPTION
**Pull request by itta611**

### CODE REVIEW

**Comment by uni-kakurenbo** [comment]
Why did you move all the modules to devDependencies?

**Comment by itta611** [comment]
To publish it as a library, we need to do so.

**Comment by uni-kakurenbo** [comment]
Please source your information.

**Comment by uni-kakurenbo** [comment]
Those packages are used in the production environment (the library itself).

**Comment by itta611** [comment]
oops.

**Comment by itta611** [comment]
fixed

**Comment by uni-kakurenbo** [comment]
Oh, sorry. `node-fetch` is not required.

**Review by uni-kakurenbo — APPROVED** [review]
Thank you so much.

**Pull request merged**
