### PR TITLE
change name to publish

### PR DESCRIPTION
**Pull request by itta611**
need to fix `@orgname/packagename`

### CODE REVIEW

**Comment by uni-kakurenbo** [comment]
Does the scope name have to be the name of the organization?
If not, I'd like to use "Scratch API Library", out of respect for Yukkku and others.

**Comment by itta611** [comment]
because i made npm org with that, And since they both mean the same thing, it's confusing to go to the trouble of giving them different names

**Comment by uni-kakurenbo** [comment]
Okay, I got it.

**Review by uni-kakurenbo — APPROVED** [review]
I think it is OK.

**Pull request merged**
